# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca7d8c8f526e2b89c9a5e2df2c972af3bf9c1814695ae506f9cb5b7b809cc400e7ade9f78ad817383a64dfa3434847a7d4cd31c55ccfa22793d9ad50db6d3d5a

test:
  secret_key_base: f536297fd224f382d4ccc9b9acbf23c90da79b963407fa57a7eb4b8d7dcb31f0a149bd9359e16ff697cc48a6eb840a8633920df64fab073dbaca1188b7f6c4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
